BloggingSystem/BloggingSystemApp/Controllers/BlogController.cs
using BloggingSystemApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BloggingSystemApp.Controllers
{
    public class BlogController : Controller
    {
        private BloggingAppDbContext db = new BloggingAppDbContext();
        // GET: Blog
        public ActionResult Index()
        {
            var blog_Posts = db.Blog_Posts.Include(b => b.Blog_Categories).Include(b => b.Blog_User);
            return View(blog_Posts.ToList());
        }
        public ActionResult MyBlogList()
        {
            Blog_User Loggeduser = (Blog_User)Session["LoggedUser"];
            try
            {
                List<Blog_Posts> MyPostList = db.Blog_Posts.Where(post => post.PostUserID == Loggeduser.UserID).ToList();
                return View("MyBlogList", MyPostList);
            }
            catch
            {
                ViewBag.NoPostsMessage = "Please add the posts";
                return View();
            }

        }

        // GET: Blog/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog_Posts blog_Posts = db.Blog_Posts.Find(id);
            if (blog_Posts == null)
            {
                return HttpNotFound();
            }
            return View(blog_Posts);
        }

        // GET: Blog_Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog_Posts blog_Posts = db.Blog_Posts.Find(id);
            if (blog_Posts == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostCategoryID = new SelectList(db.Blog_Categories, "CategoryID", "CategoryName", blog_Posts.PostCategoryID);
            ViewBag.PostUserID = new SelectList(db.Blog_User, "UserID", "UserName", blog_Posts.PostUserID);
            return View(blog_Posts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PostID,Title,PostContent")] Blog_Posts blog_Posts)
        {
            Blog_Posts EditPost = db.Blog_Posts.SingleOrDefault(post => post.PostID == blog_Posts.PostID);
            EditPost.PostContent = blog_Posts.PostContent;
            EditPost.Title = blog_Posts.Title;
            EditPost.DateModified = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Entry(EditPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MyBlogList");
            }
            ViewBag.PostCategoryID = new SelectList(db.Blog_Categories, "CategoryID", "CategoryName", blog_Posts.PostCategoryID);
            ViewBag.PostUserID = new SelectList(db.Blog_User, "UserID", "UserName", blog_Posts.PostUserID);
            return View(blog_Posts);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.PostCategoryID = new SelectList(db.Blog_Categories, "CategoryID", "CategoryName");
            ViewBag.PostUserID = new SelectList(db.Blog_User, "UserID", "UserName");
            return View();
        }

        // POST: Blog_Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,PostContent,PostCategoryID")] Blog_Posts blog_Posts)
        {
            if (ModelState.IsValid)
            {
                Blog_User user = (Blog_User)Session["LoggedUser"];
                blog_Posts.PostUserID = user.UserID;
                blog_Posts.Author = user.UserName;
                blog_Posts.DateCreated = DateTime.Now;
                blog_Posts.DateModified = DateTime.Now;
                blog_Posts.IsPublished = true;
                blog_Posts.Slug = blog_Posts.Title.Replace(" ", "_") + "_by_" + user.Name;
                db.Blog_Posts.Add(blog_Posts);
                db.SaveChanges();
                return RedirectToAction("MyBlogList");
            }

            ViewBag.PostCategoryID = new SelectList(db.Blog_Categories, "CategoryID", "CategoryName", blog_Posts.PostCategoryID);
            ViewBag.PostUserID = new SelectList(db.Blog_User, "UserID", "UserName", blog_Posts.PostUserID);
            return View(blog_Posts);
        }

        public ActionResult Delete(int id)
        {
            Blog_Posts blog_Posts = db.Blog_Posts.Find(id);
            db.Blog_Posts.Remove(blog_Posts);
            db.SaveChanges();
            return RedirectToAction("MyBlogList");
        }
    }
}

BloggingSystem/BloggingSystemApp/Controllers/LoginController.cs
using BloggingSystemApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloggingSystemApp.Controllers
{
    public class LoginController : Controller
    {
        private BloggingAppDbContext db = new BloggingAppDbContext();
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignIn([Bind(Include = "UserName, Password")]Blog_User user)
        {
            Blog_User validUser = null;
            if (ModelState.IsValid)
            {
                validUser = db.Blog_User.SingleOrDefault(usr => (usr.UserName == user.UserName && usr.Password == user.Password));
            }
            if (validUser != null)
            {
                Session["LoggedUser"] = validUser;
                Session["UserName"] = "Welcome, " + validUser.Name;

                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.LoginFailedMessage = "Login Failed! Please Try again";
                return View("Index");
            }

        }

        public ActionResult Logout()
        {
            Session["LoggedUser"] = null;
            Session["UserName"] = null;
            return RedirectToAction("Index", "Home");
        }

        public JsonResult IsUserAvailable(String UserName)
        {
            return Json(db.Blog_User.Any(usr => usr.UserName == UserName), JsonRequestBehavior.AllowGet);
        }
    }
}

BloggingSystem/BloggingSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="float-left">
                    <p class="site-title">@Html.DisplayText("Blogging System")</p>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <span class="navbar-left">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("Blogs", "Index", "Blog", new { area = "" }, null)</li>
                        @if (Session["UserName"] != null)
                        {
                            <li>@Html.ActionLink("My Blog", "MyBlogList", "Blog", new { area = "" }, null)</li>
                        }
                    </ul>
                </span>
                <span class="navbar-right">
                    <ul class="nav navbar-nav">
                        @if (Session["UserName"] != null)
                        {
                            <li style="padding-top:8%; color: #ffffff;background-color: transparent;">@Session["UserName"]</li>
                            <li>@Html.ActionLink("Logout", "Logout", "Login", new { area = "" }, null)</li>

                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Index", "Login", new { area = "" }, null)</li>
                            <li>@Html.ActionLink("Register", "Register", "Register", new { area = "" }, null)</li>
                        }
                    </ul>
                </span>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Blogging Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>